name: Deploy to EC2

on:
  push:
    branches: [ main ]
    paths: ['squiggle-web/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Build app
      run: |
        cd squiggle-web/squiggle-ui
        npm ci
        npm run build
    
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ec2-user
        SOURCE: "squiggle-web/squiggle-ui/dist/"
        TARGET: "/var/www/html/"
        SCRIPT_BEFORE: "sudo rm -rf /var/www/html/*" 